### ISSUE TITLE
Fatal Error on Multiplayer Join

### ISSUE THREAD

**Issue by feckyeslife** [andreid278/ShootIt#1]
While there is no issue with my (heavily) modded client on singleplayer, I am unable to connect to my multiplayer server with this included. Taking all mods out from the server and only loading ShootIt does not resolve the issue.

Unfortunately, there is no official *crash* associated with the error. 
On the client side, I get "A fatal error has occurred, the connection is terminated." 
On the server log, there is a "USER has disconnected, reason: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}".

**Comment by andreid278** [comment]
Which os version do you have (windows, linux, macos)?
I also need fml logs (client and server).

**Comment by andreid278** [comment]
I think i know what's wrong. What server ip do you write when you enter the server? Is it contains a port? If yes, try to use v0.1.1 and tell me about the results. Thank you.

**Comment by feckyeslife** [comment]
Yes, I do use a port to log on.

I can now connect with version 0.1.1 when both client and server have only ShootIt installed! There's a hiccup still when I try to connect with a ton of other mods, but that's more than likely a conflict on my end.
